### ISSUE TITLE
Clarify kernel-param value as string

### ISSUE THREAD

**Issue by aelsabbahy** [goss-org/goss#220]
Clarify the value is a string, to avoid users doing something like this.
```
KernelParam: net.ipv4.ip_forward: value:
Expected
    <string>: 0
to equal
    <int>: 0
```

**Comment by walidshaari** [comment]
encourge people to do : goss  add  to find the syntax too, e.g. goss  add KernelParam goss  add net.ipv4.ip_forward

**Comment by zylad** [comment]
The PR lookss good. Any chance to get it merged?

**Comment by aelsabbahy** [comment]
Need to just update the docs for now.
