### ISSUE TITLE
upstart has incorrect running check

### ISSUE THREAD

**Issue by jaymecd** [goss-org/goss#365]
Declaration in [service_upstart.go#L72](https://github.com/aelsabbahy/goss/blob/291b44151057d373db7523797e8d6bd5c7488ce0/system/service_upstart.go#L72) is incorrect command to run.

this one is for `SysV`:
```
cmd := util.NewCommand("service", s.service, "status")
```

this one is for `Upstart`:
```
cmd := util.NewCommand("initctl", "status", s.service)
```

**Comment by trevorrea** [comment]
Initctl has a different syntax than service.  For service it is

`
service servicename status
`

and for initctl it's

`
initctl status servicename`

See http://manpages.ubuntu.com/manpages/trusty/man8/initctl.8.html for details

**Comment by aelsabbahy** [comment]
Does this actually cause a false positive/negative or does service work just fine and proxy over to upstart?

**Comment by jaymecd** [comment]
There is no proxy between upstart and sysV services, unfortunately.
Upstart provides `initctl` and uses it to control jobs.

**Comment by aelsabbahy** [comment]
Did this go away as an issue? As in, does this impact any non-EOL distro?

**Comment by aelsabbahy** [comment]
Closing, if this is still an issue, please feel free to open an new report
