### ISSUE TITLE
option reable for molecule test

### ISSUE THREAD

**Issue by spham** [goss-org/goss#725]
hi
today when have error, in molecule and ansible.
we have report unreadable, like this.

![image](https://user-images.githubusercontent.com/1083631/143085578-7fec1072-695c-43fb-bec1-a361bd8a59d4.png)

why not have something like this ?
![image](https://user-images.githubusercontent.com/1083631/143085930-8f719a5f-42ae-4cac-bb5b-236fa16bc7c9.png)

it should improve debug and DX experience

**Comment by petemounce** [comment]
@spham when I use ansible I am unsatisfied with its default output too.

I tried a few options and then went with the YAML output option. https://www.jeffgeerling.com/blog/2018/use-ansibles-yaml-callback-plugin-better-cli-experience illustrates.

I thought that was a very acceptable experience for me. What do you think?

**Comment by spham** [comment]
thanks you

**Comment by spham** [comment]
when I try with ansible.cfg in same project

i have this issue

```
[defaults]
# Use the YAML callback plugin.
stdout_callback = yaml
# Use the stdout_callback when running ad-hoc commands.
bin_ansible_callbacks = True
```

failed: [] (item=/home/elk/roles/tests/templates/elastic.j2) => changed=false 
  ansible_loop_var: item
  item: /home/elk/roles/tests/templates/elastic.j2
  module_stderr: |-
    Shared connection to 172.25.192.122 closed.
  module_stdout: |-
    sudo: il est ncessaire de saisir un mot de passe
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

**Comment by petemounce** [comment]
That looks like the output format has changed to YAML as expected; is that correct?

The error seems to relate to either a dropped connection to that IP, or something in a language I don't know relating to sudo. Have you inspected the stdout/stderr as the error text suggests? 

(I think we're into ansible playbook debugging here, not Goss...?)

**Comment by ripienaar** [comment]
Sudo is trying to prompt for a password but cant without a tty, its a sudo setup issue imo

**Comment by berney** [comment]
Can this issue be closed?

**Comment by petemounce** [comment]
I think this is closeable. Please ping back if there's something further?
