### ISSUE TITLE
package scan format

### ISSUE THREAD

**Issue by AGENT3128** [goss-org/goss#776]
Hello,
Why does package_rpm.go use the format "%{VERSION}\n" in line 26? This is not the full version of the package, is it possible to fix this format '[%{VERSION}-%{RELEASE}.%{ARCH}\n]''?

**Comment by aelsabbahy** [comment]
I assume this is regarding RPM?

If so, this issue is currently tracking it: https://github.com/aelsabbahy/goss/issues/334

**Comment by aelsabbahy** [comment]
The version has been changed as of v4. There is still no rpm version comparison algorithm in goss, yet. But the needed information is there:

`%|EPOCH?{%{EPOCH}:}:{}|%{VERSION}-%{RELEASE}`

Feel free to open a new issue if you have any issues with the latest version of goss.
