### ISSUE TITLE
test python package issue while use pip

### ISSUE THREAD

**Issue by spham** [goss-org/goss#801]
I am encountering a problem while attempting to verify if a Python package, "patroni," is installed. I tried using the goss add command "patroni --version" command, which produced the following results:

As a non-root user:

```
command: 
  patroni --version:
    exit-status: 0
    stdout:
    - patroni 3.0.0
    stderr: []
    timeout: 10000
```
As the root user:

```
command:
  patroni --version:
    exit-status: 127
    stdout: []
    stderr:
    - 'sh: patroni: command not found'
    timeout: 10000
```

The "patroni" package was installed using the command python3 -m pip install patroni by a specific user. However, it appears that the goss testing tool does not have a specific method for testing packages installed with pip. This is the issue I am facing while running ansible goss tests.

How to have same behaviour like package command ? it's work on all cases

**Comment by aelsabbahy** [comment]
If you're the root user and not using Goss, can you run "patroni --version"? If you can't and see the same error when using Goss, then Goss is working properly.

I can't give technical advice right now, but if you can get it to work on the command line, then the same commands should work in Goss.

**Comment by aelsabbahy** [comment]
Hello, did the above address your question?

**Comment by aelsabbahy** [comment]
closing ticket, feel free to open a new issue if this is still a problem
