### ISSUE TITLE
Using goss to validate a remote system

### ISSUE THREAD

**Issue by TheKushIsGood** [goss-org/goss#815]
Hello

Can I use goss to validate few remote systems? Ie, i want to see if /var/tmp has the correct permission on few servers.

**Comment by aelsabbahy** [comment]
This is not supported by Goss, no.

You have a few options:

1. Wrap Goss with something that runs it remotely on those servers
2. Run `goss serve` on each server
3. You could use the `command` feature of Goss, to have the command connect to remote server and do something, basically command is open ended.

Ultimately, Goss runs on the system under tests.. it executes commands or lookups locally.

**Comment by aelsabbahy** [comment]
Closing, feel free to open up a new issue if you still have questions, bug reports, or features.
