### ISSUE TITLE
Add darwin/arm64 support

### ISSUE THREAD

**Issue by JonZeolla** [goss-org/goss#834]
**Describe the feature:**
I would like to run `goss` and the `dgoss` wrapper from on my M1 Max MBP.

**Describe the solution you'd like**
Please support and distribute binaries compiled for `darwin/arm64` so it can be used on Apple Silicon

**Describe alternatives you've considered**
I have looked at some of the existing issues and PRs, and attempted to run the `linux/arm64` binary unsuccessfully, receiving the following error:

```bash
$ goss --version
zsh: exec format error: goss
```

**Comment by aelsabbahy** [comment]
Hello, are you running goss on MacOS to test your MBP, or are you running goss in a docker container running on MacOS?

If the later, let me know if my comment [here](https://github.com/goss-org/goss/issues/823#issuecomment-1657216350) helps.

If the former, then yeah.. looks like a new binary needs to be added to the build/release process.

**Comment by JonZeolla** [comment]
👋

Right - I’m looking for support of the former to test new laptop setups. My docker / dgoss usage is not a problem (thank you for the tooling btw this is great!)

**Comment by JonZeolla** [comment]
Wow, fast turnaround time @aelsabbahy thank you

**Comment by aelsabbahy** [comment]
No problem, was a low hanging fruit.

Feel free to file any bugs/feature requests for the Mac version and/or documentation.

FYI: [Parity docs](https://github.com/goss-org/goss/blob/master/docs/platform-feature-parity.md)
