### ISSUE TITLE
Has anyone used goss in s390x environment?

### ISSUE THREAD

**Issue by harpaldhillon** [goss-org/goss#859]
Hi All,

I've a requirement to run goss compliance tests in s390x based machine. By adding new package argument (goss-linux-s390x) in the Makefile, I'm able to generate the package.

```
root@afd70aee0d65:~/goss/release# file goss-linux-s390x
goss-linux-s390x: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, Go BuildID=tfZSX6R31w5wUFueI1Ty/1qzDBlPOtkccyEZCdeWt/ahM6ZUBzz7BHD0X0I_lI/GE0PiJDQEUep19I0AeSp, stripped
```

Anyone else used goss in s390x environment?

If my tests are pass, shall I open pr for s390x packaging?

Thanks,
Harpal Dhillon

**Comment by aelsabbahy** [comment]
Closed by https://github.com/goss-org/goss/pull/863

**Comment by harpaldhillon** [comment]
Thanks @aelsabbahy
