### ISSUE TITLE
Unable to read the documentation

### ISSUE THREAD

**Issue by retr0h** [goss-org/goss#885]
**Describe the bug**

https://goss.rocks/ redirects to https://github.com/goss-org/goss

**How To Reproduce**

Click on https://goss.rocks and the static generated site is not rendered.

**Expected Behavior**

I'd be able to view the MkDocs generated site.

**Comment by ns-mjames** [comment]
@aelsabbahy  This is a big blocker for anyone who use goss and especially for anyone who are new to the ecosystem. Could you put the documentation back ?

**Comment by aelsabbahy** [comment]
Great catch, I'll fix the link tomorrow (point it to an old git sha) until the readthedocs is fully set up.

**Comment by aelsabbahy** [comment]
Apologies, didn't have time to get on the computer today. Planning on making the change tomorrow.

I'm currently on leave and am rarely on a computer.

**Comment by aelsabbahy** [comment]
I've updated the link to point to an old git sha. Please let me know if it's working well for you.

**Comment by retr0h** [comment]
> I've updated the link to point to an old git sha. Please let me know if it's working well for you.

Looks good 👍🏼 thanks!

**Comment by aelsabbahy** [comment]
Thank you for reporting and verifying.
