### ISSUE TITLE
goss.rocks/install redirects to "old" URL

### ISSUE THREAD

**Issue by dklimpel** [goss-org/goss#910]
**Describe the bug**

The setup link https://goss.rocks/install redirects to the "old" repo name: https://raw.githubusercontent.com/aelsabbahy/goss/master/install.sh

It has no impact to the content and is not a real bug.

**How To Reproduce**

Check redirect headers: https://securityheaders.com/?q=goss.rocks%2Finstall

**Expected Behavior**

Redirect to https://raw.githubusercontent.com/goss-org/goss/master/install.sh

**Comment by aelsabbahy** [comment]
Good catch, I'll fix this next week

**Comment by aelsabbahy** [comment]
Done, feel free to reopen if I'm mistaken.

Root:
https://goss.rocks ->

https://github.com/goss-org/goss

Install:
https://goss.rocks/install ->

https://raw.githubusercontent.com/goss-org/goss/master/install.sh
