### ISSUE TITLE
Dgoss Error when Running tests /goss/goss: no such file or directory.

### ISSUE THREAD

**Issue by viralsanghavi** [goss-org/goss#923]
I have my dockerfile and goss.yaml on the root level.
1. In my CICD I have first built the docker image with a tag name
2. I ran `dgoss run imageName`
3. I get this error below in the ss
<img width="1038" alt="image" src="https://github.com/goss-org/goss/assets/54470601/67c1706e-702f-4619-8d96-5e0f10c646b5">

**Comment by aelsabbahy** [comment]
My guess is either goss doesn't exist in $PATH or the goss binary architecture and container don't align.

Try setting [GOSS_PATH](https://github.com/goss-org/goss/blob/master/extras/dgoss/README.md#goss_path) to `/usr/local/bin/goss` if that doesn't work, check the architecture of the container and goss binary.

I don't like the vagueness of this error, perhaps once we identify it, the documentation or error message in dgoss can be improved.

**Comment by aelsabbahy** [comment]
Looping back on this, wondering if you had a chance to look into my suggestion above?

**Comment by aelsabbahy** [comment]
Assume this issue was resolved since I haven't gotten any feedback. Feel free to re-open or open new issue if it's not.

Thanks!
