### ISSUE TITLE
Docs: "docker" container in kgoss docs

### ISSUE THREAD

**Issue by guettli** [goss-org/goss#931]
**Describe the bug**

**How To Reproduce**

Look at https://github.com/goss-org/goss/tree/master/extras/kgoss

The term "docker container"... Afaik this is not valid anymore.

Kubernetes does no longer use docker

**Comment by dklimpel** [comment]
Do you have a recommendation? "OCI container" or anything else?

**Comment by guettli** [comment]
Yes, "OCR container" or just "container" would fit.
