### ISSUE TITLE
CVEs on goss

### ISSUE THREAD

**Issue by mstopa-splunk** [goss-org/goss#973]
**Describe the bug**
1 High, 2 Medium CVEs on goss

![image](https://github.com/user-attachments/assets/ea193f28-aa02-4343-8de5-c5be4838e93d)

**How To Reproduce**
Use [trivy](https://trivy.dev/) to detect CVE

**Expected Behavior**
Clear CVE report

**Actual Behavior**
Reported CVEe

**Environment:**
goss  v0.4.8
alpine 3.20.3

**Comment by ikheifets-splunk** [comment]
@dklimpel @aelsabbahy we ready to help add CVE detection on CI.
As I remember @dklimpel [already started tha](https://github.com/goss-org/goss/issues/903#issuecomment-2118685375)t, please let me know if I can help with that :)

**Comment by mstopa-splunk** [comment]
hi @dklimpel @aelsabbahy did you have some time to look at this?

**Comment by aelsabbahy** [comment]
Please let me know if the newest version resolves the issue for you.

**Comment by ikheifets-splunk** [comment]
> Please let me know if the newest version resolves the issue for you.

@aelsabbahy unfortunately we replaced goss to another solution, because we have strict SLA on fixing critical CVEs.
Anyway thank you for fixing.

**Comment by aelsabbahy** [comment]
Curious which solution you ended up going with.

I'll let you know once we have nightly CVE checks in case that changes anything in the future.

Many thanks for filing these and bringing this aspect to my attention as an enhancement to the release process.

**Comment by ikheifets-splunk** [comment]
> Many thanks for filing these and bringing this aspect to my attention as an enhancement to the release process.

Thank you too, I super glad that we have such good communication :)

> Curious which solution you ended up going with.

Instead of using generic tools for healthchecking, we found optimised for our use case - health check for syslog server by syslog-ng
